name = "wedding-site"
compatibility_date = "2024-01-18"

main = "./.svelte-kit/cloudflare/_worker.js"

[site]
bucket = "./.svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "wedding-rsvps"
database_id = "107ff1a2-e3a8-4f71-9a67-c3992d7a4f29"
preview_database_id = "f9112b4d-82f1-4505-bc8f-2a55b755ae64"

[dev]
port = 8788