name = "wedding-website"
compatibility_date = "2024-01-18"
main = "./.svelte-kit/cloudflare/_worker.js"

# Preview environment (covers both dev and staging branches)
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "wedding-rsvps-preview"
database_id = "581d792c-603c-4a42-a9c4-c3dc69c8d41d"

# Production environment
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "wedding-rsvps-prod"
database_id = "5f4ee888-0757-44bf-8a69-49566936ae45"
routes = [
  { pattern = "/admin*", zone_name = "martinelliotoole.com" }
]

# Development configuration
[dev]
port = 8788