name = "wedding-website"
compatibility_date = "2024-01-18"

# Define the main worker entry point
main = "./.svelte-kit/cloudflare/_worker.js"

# Local D1 database
[[d1_databases]]
binding = "RSVPS"
database_name = "wedding-rsvps-preview"
database_id = "581d792c-603c-4a42-a9c4-c3dc69c8d41d"

# Local KV store
[[kv_namespaces]]
binding = "IMAGES_KV"
id = "wedding-images-kv-preview"
preview_id = "wedding-images-kv-preview"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "wedding-images-preview"
preview_bucket_name = "wedding-images-kv-preview"

# Preview environment configuration
[env.preview]
[[env.preview.d1_databases]]
binding = "RSVPS"
database_name = "wedding-rsvps-preview"
database_id = "581d792c-603c-4a42-a9c4-c3dc69c8d41d"
preview_database_name = "wedding-rsvps-preview"
preview_database_id = "581d792c-603c-4a42-a9c4-c3dc69c8d41d"

[[env.preview.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "wedding-images-preview"

[[env.preview.kv_namespaces]]
binding = "IMAGES_KV"
id = "wedding-images-kv-preview"

# Production environment configuration
[env.production]
[[env.production.d1_databases]]
binding = "RSVPS"
database_name = "wedding-rsvps-prod"
database_id = "5f4ee888-0757-44bf-8a69-49566936ae45"

[[env.production.r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "wedding-images-prod"

[[env.production.kv_namespaces]]
binding = "IMAGES_KV"
id = "wedding-images-kv-prod"

# Development configuration
[dev]
port = 8788
ip = "localhost"

# Build configuration
[build]
command = "npm run build"
watch_dir = "src"

[vars]
ENVIRONMENT = "development"

[env.preview.vars]
ENVIRONMENT = "preview"

[env.production.vars]
ENVIRONMENT = "production"