name = "wedding-site"
compatibility_date = "2024-01-18"
main = "./.svelte-kit/cloudflare/_worker.js"

# Development environment
[env.dev]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "wedding-rsvps-dev"
database_id = "f9112b4d-82f1-4505-bc8f-2a55b755ae64"

# Staging environment
[env.staging]
[[env.staging.d1_databases]]
binding = "DB"
database_name = "wedding-rsvps-staging"
database_id = "a5281586-242d-45f0-8133-3d9ce550672d"

# Production environment
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "wedding-rsvps-prod"
database_id = "5f4ee888-0757-44bf-8a69-49566936ae45"
routes = [
  { pattern = "/admin*", zone_name = "martinelliotoole.com" }
]

# Development configuration
[dev]
port = 8788